---
# Source: helm for kubernetes/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dara-9b8b6ddc                  # Ingress name
  labels:
    app: dara-9b8b6ddc
spec:
  ingressClassName: nginx   # Optional ingressClass
  rules:
    - host: "dara-9b8b6ddc.smartops.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dara-9b8b6ddc               # Links to Service name dynamically
                port:
                  number: 8080  # Links to service port dynamically
